--1. List all films with their titles and release years.--
SELECT title,release_year FROM film;
      
--2. Find the total number of films in the database.--
SELECT COUNT(*) FROM film;

--3. Show the names of all customers who rented at least one film. --
SELECT  DISTINCT customer.first_name,customer.last_name FROM customer
JOIN rental ON customer.customer_id=rental.customer_id;

--4. Retrieve the titles of films in the “Action” category.--
SELECT film.title FROM film JOIN film_category ON film.film_id=film_category.film_id
JOIN category ON film_category.category_id=category.category_id WHERE category.name='Action';

--5. Count how many films belong to each category.--
SELECT category.name AS category_name,COUNT(film_category.film_id) AS fcount
FROM category JOIN film_category ON
category.category_id=film_category.category_id 
GROUP BY category.name
ORDER BY fcount DESC;

--6. Display the top 5 longest films by length.--
SELECT title,film.length FROM film ORDER BY film.length DESC LIMIT 5;

--7. Find the number of rentals made in January 2006.--
SELECT COUNT(*) AS rental_count FROM rental 
WHERE rental_date>='2006-01-01 00:00:00' 
AND rental_date<'2006-02-01 00:00:00';

--8. Show all films that have rental rates greater than $3.--
SELECT * FROM film WHERE rental_rate>3;

--9. List all distinct cities where customers live. --
SELECT DISTINCT city.city FROM city 
JOIN address ON city.city_id=address.city_id 
JOIN customer ON customer.address_id=address.address_id;

--10. Find the staff members who processed rentals.--
SELECT DISTINCT staff.staff_id,(staff.first_name||''||staff.last_name)AS staff_name 
FROM staff JOIN rental ON rental.staff_id=staff.staff_id;


--11. Find the top 10 films by number of rentals. --
SELECT film.title,COUNT (*) AS rental_count FROM rental 
JOIN inventory ON rental.inventory_id=inventory.inventory_id
JOIN film ON film.film_id=inventory.film_id GROUP BY film.title
ORDER BY rental_count DESC LIMIT 10;

--12. Show the revenue generated by each film (sum of payments). 
SELECT film.title,SUM(payment.amount) AS revenue FROM payment
JOIN rental ON rental.rental_id=payment.rental_id 
JOIN inventory ON rental.inventory_id=inventory.inventory_id
JOIN film ON film.film_id=inventory.film_id GROUP BY film.title;


--13. List customers who rented more than 20 films.--
SELECT (customer.first_name||' '||customer.last_name) AS customername FROM customer 
JOIN rental ON rental.customer_id = customer.customer_id
GROUP BY customer.customer_id HAVING COUNT(rental.customer_id)>20;


SELECT (customer.first_name||' '||customer.last_name) AS customername,COUNT(rental.customer_id) AS rentalcount
FROM customer 
JOIN rental ON rental.customer_id = customer.customer_id
GROUP BY customer.customer_id HAVING COUNT(rental.customer_id)>20;

--14. Find the average rental duration for each category. --
SELECT category.name,AVG(rental_duration) AS avgrentalduration
FROM category 
JOIN film_category ON  category.category_id=film_category.category_id
JOIN film ON film.film_id=film_category.film_id GROUP BY category.name;


--15. Display films that were rented but never returned late. --
SELECT DISTINCT film.title FROM film JOIN inventory ON inventory.film_id = film.film_id 
JOIN rental ON rental.inventory_id = inventory.inventory_id
WHERE film.film_id NOT IN ( SELECT film.film_id FROM film 
JOIN inventory ON inventory.film_id = film.film_id JOIN rental ON rental.inventory_id = inventory.inventory_id
WHERE rental.return_date IS NOT NULL AND (rental.return_date - rental.rental_date) > (film.rental_duration * INTERVAL '1 day'));



--16. Identify the most popular film category by rental count. __
SELECT category.name,COUNT(inventory.inventory_id)AS rentalcount FROM category
JOIN film_category ON film_category.category_id=category.category_id 
JOIN inventory ON inventory.film_id=film_category.film_id 
JOIN rental ON rental.inventory_id = inventory.inventory_id 
GROUP BY category.name ORDER BY rentalcount DESC LIMIT 1;

--17. Show the monthly rental count trend for 2005–2006. --
SELECT to_char(rental_date,'MONTH') AS month,
COUNT (*) FROM rental
WHERE rental_date >= '2005-01-01'
AND rental_date <  '2007-01-01'
GROUP BY month ORDER BY MIN(rental_date);


--18. Find customers who rented films from more than 5 categories. --
SELECT (customer.first_name||' '||customer.last_name) AS customername,
COUNT(DISTINCT film_category.category_id) as CatCount
FROM customer 
JOIN rental ON customer.customer_id=rental.customer_id 
JOIN inventory ON rental.inventory_id=inventory.inventory_id
JOIN film ON film.film_id = inventory.film_id
JOIN film_category ON film_category.film_id=film.film_id GROUP BY customer.first_name,customer.last_name
HAVING COUNT(DISTINCT film_category.category_id)>5;


--19. List films that were rented by customers from Canada. --
SELECT DISTINCT film.title FROM film 
JOIN inventory ON inventory.film_id=film.film_id
JOIN rental ON inventory.inventory_id=rental.inventory_id 
JOIN customer ON customer.customer_id=rental.customer_id
JOIN address ON customer.address_id=address.address_id
JOIN city ON address.city_id=city.city_id
JOIN country ON country.country_id=city.country_id 
WHERE country.country='Canada';

--20. Show the top 5 customers by total payment amount.--
SELECT (customer.first_name||' '||customer.last_name)AS customername,
SUM(payment.amount) AS TotalPay FROM customer 
JOIN payment ON customer.customer_id=payment.customer_id 
GROUP BY customer.first_name,customer.last_name ORDER BY SUM(payment.amount) DESC LIMIT 5;


--21. Use a window function to rank films by rental frequency.--
SELECT film.title,
COUNT(rental.rental_id) AS rentalcount,
RANK() OVER (ORDER BY COUNT(rental.rental_id) DESC) AS rank FROM film
JOIN inventory ON inventory.film_id = film.film_id
JOIN rental ON rental.inventory_id = inventory.inventory_id GROUP BY film.title;

--22. Create a CTE to calculate monthly revenue and display the top 3 months. --
WITH monthly_revenue AS (SELECT DATE_TRUNC('month', rental.rental_date) AS month,
           SUM(payment.amount) AS revenue FROM payment JOIN rental ON rental.rental_id = payment.rental_id
    GROUP BY month)
SELECT month, revenue FROM monthly_revenue ORDER BY revenue DESC LIMIT 3;

--23. Find films that generated revenue above the overall average.--
SELECT film.title, SUM(payment.amount) AS revenue
FROM film
JOIN inventory ON inventory.film_id = film.film_id
JOIN rental ON rental.inventory_id = inventory.inventory_id
JOIN payment ON payment.rental_id = rental.rental_id
GROUP BY film.title
HAVING SUM(payment.amount) >
(
    SELECT AVG(total_revenue)
    FROM (
        SELECT SUM(payment.amount) AS total_revenue
        FROM film
        JOIN inventory ON inventory.film_id = film.film_id
        JOIN rental ON rental.inventory_id = inventory.inventory_id
        JOIN payment ON payment.rental_id = rental.rental_id
        GROUP BY film.film_id
    ) avg_table
);

--24. Write a query to calculate customer lifetime value (total payments per customer). --
SELECT (customer.first_name || ' ' || customer.last_name) AS customername,
SUM(payment.amount) AS total_payment
FROM customer
JOIN payment ON customer.customer_id = payment.customer_id
GROUP BY customer.customer_id, customer.first_name, customer.last_name
ORDER BY total_payment DESC;

--25. Identify films that were rented in consecutive months. --
WITH film_months AS (
    SELECT film.film_id,
           film.title,
           DATE_TRUNC('month', rental.rental_date) AS month
    FROM film
    JOIN inventory ON inventory.film_id = film.film_id
    JOIN rental ON rental.inventory_id = inventory.inventory_id
),
ranked_months AS (
    SELECT film_id, title, month,
           LAG(month) OVER (PARTITION BY film_id ORDER BY month) AS prev_month
    FROM film_months
)
SELECT DISTINCT title
FROM ranked_months
WHERE month = prev_month + INTERVAL '1 month';

--26. Create a materialized view showing film popularity by category. --
DROP MATERIALIZED VIEW film_popularity_by_category;

CREATE MATERIALIZED VIEW film_popularity_by_category AS
SELECT category.name AS category,
       film.title,
       COUNT(rental.rental_id) AS rentalcount
FROM category
JOIN film_category ON film_category.category_id = category.category_id
JOIN film ON film.film_id = film_category.film_id
JOIN inventory ON inventory.film_id = film.film_id
JOIN rental ON rental.inventory_id = inventory.inventory_id
GROUP BY category.name, film.title;


--27. Write a stored procedure to calculate revenue for a given film ID. --
CREATE OR REPLACE FUNCTION film_revenue(fid INT)
RETURNS NUMERIC AS $$
BEGIN
    RETURN (
        SELECT SUM(payment.amount)
        FROM film
        JOIN inventory ON inventory.film_id = film.film_id
        JOIN rental ON rental.inventory_id = inventory.inventory_id
        JOIN payment ON payment.rental_id = rental.rental_id
        WHERE film.film_id = fid
    );
END;
$$ LANGUAGE plpgsql;

SELECT film_revenue(20);


--28. Build a trigger that logs whenever a rental is returned late. --
CREATE TABLE late_return_log (
    rental_id INT,
    returned_on TIMESTAMP,
    late_days INT
);


CREATE OR REPLACE FUNCTION log_late_return()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.return_date IS NOT NULL
       AND (NEW.return_date - NEW.rental_date)
           > (SELECT rental_duration * INTERVAL '1 day'
              FROM film
              JOIN inventory ON inventory.film_id = film.film_id
              WHERE inventory.inventory_id = NEW.inventory_id)
    THEN
        INSERT INTO late_return_log
        VALUES (
            NEW.rental_id,
            NEW.return_date,
            EXTRACT(DAY FROM (NEW.return_date - NEW.rental_date))
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER late_return_trigger
AFTER UPDATE OF return_date ON rental
FOR EACH ROW
EXECUTE FUNCTION log_late_return();

UPDATE rental
SET return_date = rental_date + INTERVAL '20 days'
WHERE rental_id = 1;

SELECT * FROM late_return_log ORDER BY returned_on DESC;


--29. Partition rentals by year & yearly revenue--
SELECT EXTRACT(YEAR FROM rental.rental_date) AS year,
SUM(payment.amount) AS revenue
FROM rental
JOIN payment ON payment.rental_id = rental.rental_id
GROUP BY year
ORDER BY year;


--30. Optimize a query using indexes to speed up film search by title.--
CREATE INDEX idx_film_title ON film(title);

SELECT *
FROM film
WHERE title ILIKE '%ACADEMY%';

EXPLAIN ANALYZE
SELECT *
FROM film
WHERE title ILIKE '%ACADEMY%';